version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: test1
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test1
    ports:
      - "127.0.0.1:5432:5432"

